version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: taskList-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: local-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ../:/app
    command: sh -c "composer install --ignore-platform-reqs && cp .env.example .env"
  db:
    container_name: tasks-db
    image: mysql:8.0
    volumes:
        - ./storage/mysql:/var/lib/mysql
        - ./:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3305:3306